	//Mensajes de Error
	#define error_usb_rf		  "no puede conectar, USB RF No detectado.\r\nFuncion ConnectMoway."
	#define error_moway_off		  "Moway no detectado. Debe estar encendido y en el canal correcto.\r\nFuncion ConnectMoway."
    #define error_moway_no_answer "Moway no ha respondido la petición de conexion.\r\nFuncion ConnectMoway."
	#define error_disconnect	  "No se puede desconectar,\r\nFuncion DisconnectMoway."
    #define error_leds            "Error LEDS.\r\nFuncion ChangeLEDState."
    #define error_speed_left      "Error rueda izquierda.\r\nFuncion SetSpeed."
    #define error_speed_right     "Error rueda derecha.\r\nFuncion SetSpeed."
    #define error_goStraight      "Error en Funcion GoStraight."
    #define error_battery         "Error en Funcion ReadBatteryStatus."
    #define error_temp            "Error en Funcion ReadTemp."
    #define error_light_sensor    "Error en Funcion ReadAmbientLightSensor."
    #define error_get_speed_left  "Error leyendo la velocidad de la rueda izquierda.\r\nFuncion ReadSpeed."
    #define error_get_speed_right "Error leyendo la velocidad de la rueda derecha.\r\nFuncion ReadSpeed."
    #define error_motor_stop      "Error en Funcion MotorStop."
    #define error_motor_dist_rst  "Error en Funcion MotorDistanceReset."
    #define error_motor_km_rst    "Error en Funcion MotorKmReset."
    #define error_motor_time_rst  "Error en Funcion MotorTimeReset."
    #define error_distance_left   "Error leyendo distancia rueda izquierda.\r\nFuncion ReadMotorDistances"
    #define error_distance_right  "Error leyendo distancia rueda derecha.\r\nFuncion ReadMotorDistances"
    #define error_prox            "Error leyendo sensor prox \r\nFuncion ReadProximitySensors"
    #define error_line            "Error leyendo sensor linea \r\nFuncion ReadProximitySensors"
    #define error_rotation_left   "Error leyendo rotacion rueda izquierda.\r\nFuncion ReadWheelRotation"
    #define error_rotation_right  "Error leyendo rotacion rueda derecha.\r\nFuncion ReadWheelRotation"
    #define error_RF_general      "General RF Module ERROR\r\n"
    #define error_receive         "Error al recibir\r\n"
    #define error_send            "Error al enviar\r\n"
    #define error_libusb          "Libusb no iniciado\r\n"
    #define error_motor_time      "Error en Funcion ReadMotorTime\r\n"
    #define error_axis            "Error en Funcion ReadAccelerator\r\n"
    #define error_speaker         "Error en Funcion SetSpeaker\r\n"